name: birdbreeder
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.19.3


dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2
  awesome_extensions: ^2.0.20
  bloc: ^9.1.0
  bloc_presentation: ^1.0.0
  custom_refresh_indicator: ^4.0.1
  pocketbase_drift: ^0.3.2
  collection: ^1.17.1
  dartx: ^1.2.0
  dropdown_search: ^6.0.2
  equatable: ^2.0.5
  url_launcher: ^6.3.2
  flash: ^3.0.5+1
  flutter_colorpicker: ^1.1.0
  flutter_bloc: ^9.1.1
  data_table_2: ^2.6.0
  freezed_annotation: ^3.1.0
  get_it: ^9.1.0
  pocketbase: ^0.23.0+1
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  sidebarx: ^0.17.1
  json_annotation: ^4.9.0
  path: ^1.8.2
  path_provider: ^2.1.5
  logger: ^2.5.0
  easy_autocomplete: ^1.6.0
  shared_preferences: ^2.5.3
  dio: ^5.1.1
  uuid: ^4.5.2
  # https://appainter.dev/
  json_theme: ^11.0.0
  flutter_localizations:
    sdk: flutter
  auto_mappr_annotation: ^2.2.0
  auto_route: ^10.2.3
  flex_color_scheme: ^8.1.0
  slang: ^4.8.1
  slang_flutter: ^4.8.0



# Overritten because of the issue with the win32 package and the archive package because they are using
# a removed list from the dart SDK. Please remove this when the issue is fixed.
# Last checked: 2024-10-02
dependency_overrides:
  win32: ^5.5.3
  archive: ^3.6.1
  meta: ^1.16.0
  

dev_dependencies:
  auto_mappr: ^2.5.0
  auto_route_generator: ^10.2.6
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  custom_lint: ^0.8.1
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  very_good_analysis: ^10.0.0
  slang_build_runner: ^4.8.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/themes/
    - assets/images/
    - assets/

