name: birdbreeder
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.10.5


dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4  
  async: ^2.8.2
  bloc: ^8.1.1
  collection: ^1.17.1
  equatable: ^2.0.5
  flash: ^3.0.5+1
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.2
  path: ^1.8.2
  path_provider: ^2.0.15
  responsive_framework: ^1.1.0
  shared_preferences: ^2.0.15
  auto_route: 7.8.0
  dio: ^5.1.1
  uuid: ^3.0.6




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.1
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_gen:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

